### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HyperCommNet** [PaycoinFoundation/paycoin#147]
"errors" : "EXCEPTION: St9bad_alloc       \nstd::bad_alloc       \npaycoin in ProcessMessages()       \n"

**Comment by mitchellcash** [comment]
How much memory do you have on the machine that is producing that error?

**Comment by mitchellcash** [comment]
It's seems like almost certainly a memory or address space issue. I've read you can try:
`sysctl vm.overcommit_memory=1`
But this is temporary and will be lost at reboot. Best fix is to get more memory.

**Comment by IngCr3at1on** [comment]
Yeah, I've seen reports of this happening on other coins (including bitcoin). Some have said it was in relation to the addr.dat file but I expect the overall reason is the same as @mitchellcash mentioned.

**Comment by IngCr3at1on** [comment]
I have a sneak suspicion this is fixed in PR #183

**Comment by IngCr3at1on** [comment]
Anyone ever determine if this was resolved?

**Comment by mitchellcash** [comment]
I never experienced the issue and still do not so I'm not much help here :P
